export default {
  body: document.querySelector('body'),
  authBlock: document.querySelector('.header-auth'),
  authBlockMobile: document.querySelector('.header-auth-mobile'),
  clearBlock: document.querySelector('.clear-filters-wrapper'),
  clearBlockMobile: document.querySelector('.mobile-clear-filters-wrapper'),
  mobileMenuClosed: document.querySelector('.mobile-menu-closed'),
  mobileMenuOpened: document.querySelector('.mobile-menu-opened'),
  mobileFiltersBtn: document.querySelector('.mobile-filters-wrapper'),
  categories: document.querySelector('.categories-filter'),
  categoriesMobile: document.querySelector('.categories-filter-mobile'),
  categoriesTablet: document.querySelector('.categories-filter-tablet'),
  tabletFiltersBtn: document.querySelector('.filters-wrapper'),
  mobileBurger: document.querySelector('.mobile-burger'),
  mobileSearch: document.querySelector('.mobile-search'),
  mobileInput: document.querySelector('.mobile-input-closed'),
  inputSearch: document.querySelector('.mobile-input-btn'),
  inputCross: document.querySelector('.mobile-input-cross'),
  cross: document.querySelector('.close-menu'),
};
